on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Testing action
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test action
        id: test
        uses: grantmcconnaughey/lintly-flake8-github-action@f2dd9eb
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
